# Generated by Django 2.2.9 on 2020-02-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('description', models.CharField(max_length=255, verbose_name='package description')),
                ('is_fragile', models.BooleanField(default=False)),
                ('weight', models.CharField(max_length=50, verbose_name='package weight')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
